# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:eWVXloHIO94iiuxu9Jcpg04+G8GvlSw=,iv:rdaDjzXGm8ClUQoRv/FCKyumHr/SvFR+95sfkrxZuk4=,tag:i2rotNT5gxREOOpvb2OW/g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:MOESkkfZN8jp+9ijizKssHSTzAjb5xOLdJ8b88OeG1V/MUSHRA==,iv:jfDTxz189sbkG2X3wbi99ULpeiqiD4+/jyZl9ATIwVQ=,tag:NEkV3sa7LGwsgspkYq9niQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:RtmViqscM3lDcdGyIAk62Wy8vKc/AQ==,iv:Mn+12cdv0dusVGhMWoRzn9Ey4HLSb9saAWAA7BqeTOc=,tag:e4vA1SF0WG2BkbG0aRuI9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lykec5u3g8w44ngap7kj99xdp7nu9f02mk9tc7c4ahk23xd8npksqtahuf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY2Z4NGlWVnZrU04zN1Jx
            RGhIcHh0Rk8rS08xbU14Rm9iclRwdHkySmxBClRueEZCb1MwU25NUUYyanhkSm1F
            cWtsWXZ0OEtVdW9CMnhHY2hHUlE4clkKLS0tIEp1bkFsamtiT0ROVkFYMVIyRldS
            ay9YaUsyR0M4Sno2VitiSFh6UzRjaG8Kft+hKF+xvpM7L00gTg7KL9pYBqTlK4to
            fRy1pV/fSTUeUdeHKAokJAO8qdm4FW2CEQ/wrwnLPp+LNomkrBm+Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-19T15:03:32Z"
    mac: ENC[AES256_GCM,data:r5Ydt/6+vTyTe69QqZ+uAHSUhH2m0uRU/yZo2MPzHIMbJE6ppbd2DgOiHjH2VIL5ZFmhFX615UKzpdR4zFh9xs0N1wokB76H+4us/xFCml5WLvL0IIi/9ix7hSyxGte2iEmMVs47fQFyL8usDIUFqR2ca3OT8MedPBPccuRWAMQ=,iv:VH5uRjhRJt3p4PBY42Pz4muyF8ho/IUK5Ezl0MF0z8k=,tag:BocEo8HCx01qCaqy0xdeIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
