---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ghost
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghost
      tag: 4.27.2
      pullPolicy: IfNotPresent
    # See https://ghost.org/docs/config/#running-ghost-with-config-env-variables
    env:
      url: "http://ghost.brendonmccool.com"
      database__client: mysql
      database__connection__host: ghost-mariadb
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      NODE_ENV: production
    service:
      main:
        ports:
          http:
            port: 2368
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "ghost.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ghost.${SECRET_DOMAIN}"
            secretName: "ghost-tls"

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      content:
        enabled: true
        mountPath: /var/lib/ghost/content

    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: ghost
        username: ghost
        password: ghost
        rootPassword: ghost-rootpass
      primary:
        persistance:
          enabled: true
