---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    #image:
    #  repository: ghcr.io/k8s-at-home/uptime-kuma
    #  tag: v1.11.1
    #  pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "uptime-kuma.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "uptime-kuma.${SECRET_DOMAIN}"
            secretName: "uptime-kuma-tls"
    #persistence:
    #  data:
    #    enabled: false
    #    existingClaim: uptime-kuma-config
    #podAnnotations:
    #  configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
