---
kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
        k3s-master-1:
        k3s-master-2:
    worker:
      hosts:
        k3s-worker-0:
        k3s-worker-1:
        k3s-worker-2:
        k3s-worker-3:
